import Head from "next/head"
import { Inter } from "@next/font/google"
import { useEffect, useRef, useState } from "react"
import { css } from "@emotion/react"
import { Button } from "@components/Button"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null)
  const [productcs, setProducts] = useState<
    {
      id: string
      name: string
      createdAt: string
    }[]
  >([])

  useEffect(() => {
    fetch("/api/get-products")
      .then((res) => res.json())
      .then((data) => setProducts(data.items))
  }, [])

  const handleClick = () => {
    if (!inputRef.current || inputRef.current?.value === "") {
      alert("name을 넣어주세요")
      return
    }

    fetch(`/api/add-item?name=${inputRef.current.value}`)
      .then((res) => res.json())
      .then((data) => alert(data.message))
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input
        className="placeholder:italic placeholder:text-slate-400 block bg-white w-96 border border-slate-300 rounded-md py-2 pl-3 pr-3 shadow-sm focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 sm:text-sm"
        placeholder="Search for anything..."
        type="text"
        name="search"
      />
      <Button>제출</Button>
      <main>
        {productcs &&
          productcs.map((item) => (
            <div key={item.id}>
              {item.name} {item.createdAt}
            </div>
          ))}
      </main>
    </>
  )
}
